### ISSUE TITLE
Migrate this repository to WICG

### ISSUE THREAD

**Issue by msporny** [WICG/web-payments-browser-api#1]
Hey @yoavweiss @marcoscaceres @darobin - I have no idea how this new fangled WICG is supposed to work, but could you please migrate this repo over to WICG? I have signed up for the WICG IPR, run the ash-nazg thingermabobber on the repo, and sacrificed at least three chickens.

**Comment by marcoscaceres** [comment]
The chickens are what are most important 👹. We just need to transfer it over to the WICG now through github's setting for the repo. Will try to do that.

**Comment by marcoscaceres** [comment]
Oki, transferred. Let me know if there is anyone else should be on your editorial team?

**Comment by msporny** [comment]
@marcoscaceres, other editorial team members: @dlongley @davidlehn @mattcollier

**Comment by marcoscaceres** [comment]
Closing loop here... @yoavweiss added the above folks.
